### ISSUE TITLE
Won't build with java10?

### ISSUE THREAD

**Issue by bklarson** [jendap/multiplatform-swt#1]
I'm getting a maven error when trying to run 'mvn install' with java 10.0.1 64-bit:

Running com.janprach.multiplatformswt.MultiPlatformSwtHelperIT
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.064 sec <<< FAILURE! - in com.janprach.multiplatformswt.MultiPlatformSwtHelperIT
importSwtJarUninitializedSystemClassLoaderTest(com.janprach.multiplatformswt.MultiPlatformSwtHelperIT)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.ClassNotFoundException> but was<java.lang.ClassCastException>
        at com.janprach.multiplatformswt.MultiPlatformSwtHelperIT.importSwtJarUninitializedSystemClassLoaderTest(MultiPlatformSwtHelperIT.java:18)

**Comment by jendap** [comment]
Hi, I'm sorry I have not noticed this issue. It was fixed. But then it was completely rewritten. If you are still using swt you may check it out. It should be better :)
